apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfapm.fullname" . }}-apm
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: server
    snappyflow/component: snappyflow-apm
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
{{- if not .Values.sfapm.autoscaling.enabled }}
  replicas: {{ .Values.sfapm.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sfapm.selectorLabels" . | nindent 6 }}
      app: sfapm
      role: server
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sfapm.selectorLabels" . | nindent 8 }}
        app: sfapm
        role: server
        snappyflow/component: snappyflow-apm
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sfapm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.global.enable_sftrace }}
        - name: pythonagent
          image: busybox
          command:
            - sh
            - -c
            - -x
            - wget -O /sfagent/sftrace-agent.tar.gz https://github.com/snappyflow/apm-agent/releases/download/latest/sftrace-agent.tar.gz && cd /sfagent && tar -xvzf sftrace-agent.tar.gz && rm sftrace-agent.tar.gz
          volumeMounts:
          - mountPath: /sfagent
            name: python-agent
        {{- end }}
        - name: db-ready
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - "until pg_isready -d postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}; do sleep 3; done"
          {{- if .Values.postgresql.enabled }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
        - name: redis-ready
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - "until redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} ping ; do sleep 3; done"
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
        - name: pre-migration-setup
          image: "{{ .Values.sfapm.image.repository }}:{{ .Values.sfapm.image.tag }}"
          imagePullPolicy: Always
          command:
            - bash 
            - -c
            - "python /app/scripts/pre_python3_migration.py"
          {{- if .Values.postgresql.enabled }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
        - name: migration
          image: "{{ .Values.sfapm.image.repository }}:{{ .Values.sfapm.image.tag }}"
          imagePullPolicy: {{ .Values.sfapm.image.pullPolicy }}
          command: ["bash"]
          # args: ["-c", "python manage.py makemigrations && python manage.py migrate"]
          args: ["-c", "python manage.py migrate administration --fake-initial; python manage.py migrate"]
          env:
          {{- if .Values.postgresql.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm 
          volumeMounts:
            - mountPath: /data/snappyflow
              name: data
      containers:
        - name: sfapm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sfapm.image.repository }}:{{ .Values.sfapm.image.tag }}"
          {{- if .Values.global.enable_sftrace }}
          command:
            - sh
            - -c
            - /sfagent/sftrace/sftrace --sfcmd="gunicorn snappyflow.wsgi:application"
          {{- end }}
          imagePullPolicy: {{ .Values.sfapm.image.pullPolicy }}
          env:
          {{- if .Values.global.enable_sftrace }}
            - name: SFTRACE_PROFILE_KEY
              value: "{{ .Values.global.key }}"
            - name: SFTRACE_PROJECT_NAME
              value: "{{ .Values.global.sfprojectname }}"
            - name: SFTRACE_APP_NAME
              value: "{{ .Values.global.sfappname }}"
            - name: ENABLE_SFTRACE
              value: "{{ .Values.global.enable_sftrace }}"
          {{- end }}
          {{- if .Values.postgresql.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          {{- if .Values.enableDebug }}
            - name: DEBUG
              value: "True"
          {{- end }}
          {{- if .Values.enableDebug }}
            - name: LOG_LEVEL
              value: debug
          {{- else }}
            - name: LOG_LEVEL
              value: info
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm                   
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /snappyflow/status
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /snappyflow/status
              port: http
          resources:
            {{- toYaml .Values.sfapm.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/snappyflow
              name: data
            - name: pluginmapping
              mountPath: /app/snappyflow/plugin_info
            - name: snappyflowlog
              mountPath: /var/log/snappyflow/
            {{- if .Values.global.enable_sftrace }}
            - mountPath: /sfagent
              name: python-agent
            {{- end }}
        {{- if .Values.sidecarLogger.enabled }}
        - name: application-logger
          image:  "{{ .Values.sidecarLogger.image.repository }}:{{ .Values.sidecarLogger.image.tag }}"
          imagePullPolicy: {{ .Values.sidecarLogger.image.pullPolicy | quote }}
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/snappyflow/snappyflow.log']
          resources:
            {{- toYaml .Values.sidecarLogger.resources | nindent 12 }}
          volumeMounts:
          - name: snappyflowlog
            mountPath: /var/log/snappyflow/
        {{- end }}
        {{- if .Values.sidecarLogger.enabled }}
        - name: audit-logger
          image:  "{{ .Values.sidecarLogger.image.repository }}:{{ .Values.sidecarLogger.image.tag }}"
          imagePullPolicy: {{ .Values.sidecarLogger.image.pullPolicy | quote }}
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/snappyflow/audit.log']
          resources:
            {{- toYaml .Values.sidecarLogger.resources | nindent 12 }}
          volumeMounts:
          - name: snappyflowlog
            mountPath: /var/log/snappyflow/
        {{- end }}
        {{- if .Values.mappingUpdator.enabled }}
        - name: plugin-mapping-updator
          image: "{{ .Values.mappingUpdator.image.repository }}:{{ .Values.mappingUpdator.image.tag }}"
          command: ["/bin/sh","-c"]
          args: ["cp -r /app/plugin_info/* /mappings/ && /app/plugin-mapping-updator --git_branch release --update_remote_git=false --local_root_mapping_dir /mappings/"]
          resources:
            {{- toYaml .Values.mappingUpdator.resources | nindent 12 }}
          env:
          {{- if .Values.postgresql.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
          volumeMounts:
          - name: pluginmapping
            mountPath: /mappings/
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sfapmaffinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: snappyflowlog
          emptyDir: {}
        - name: pluginmapping
          emptyDir: {}
        {{- if .Values.global.enable_sftrace }}
        - name: python-agent
          emptyDir: {}
        {{- end }}
