apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
#{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "keycloak.fullname" . }}-headless
#{{- end }}
  serviceName: {{ include "keycloak.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: db-ready
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - "until pg_isready -d postgres://${DB_USER}:${DB_PASSWORD}@${DB_ADDR}:${DB_PORT}/${DB_DATABASE}; do sleep 3; done"
          {{- if .Values.postgresql.enabled }}
          env:
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.keycloak.tls.enabled }}
          ports:
            - name: https
              containerPort: 8443
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
          volumeMounts:
          - name: certs
            mountPath: /etc/x509/https
            readOnly: true
          {{- range $key, $value := .Values.startupScripts }}
          - name: startup
            mountPath: "/opt/jboss/startup-scripts/{{ $key }}"
            subPath: "{{ $key }}"
            readOnly: true
          {{- end }}
          {{- else }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
          volumeMounts:
          {{- range $key, $value := .Values.startupScripts }}
          - name: startup
            mountPath: "/opt/jboss/startup-scripts/{{ $key }}"
            subPath: "{{ $key }}"
            readOnly: true
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.keycloak.tls.enabled }}          
          - name: X509_CA_BUNDLE
            value: /etc/x509/https/tls.crt /etc/x509/https/tls.key
          {{- end }}
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: DB_VENDOR
            value: "postgres"
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: dns.DNS_PING
          - name: JGROUPS_DISCOVERY_PROPERTIES
            value: 'dns_query={{ include "keycloak.serviceDnsName" . }}'
          - name: CACHE_OWNERS_COUNT
            value: "2"
          - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
            value: "2"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
      volumes:
      {{- if .Values.keycloak.tls.enabled }}
        - name: certs
          secret:
            secretName: {{ .Release.Name }}-tls
      {{- end }}
      {{- with .Values.startupScripts }}
        - name: startup
          configMap:
            name: {{ include "keycloak.fullname" $ }}-startup
            defaultMode: 0555
            items:
              {{- range $key, $value := . }}
              - key: {{ $key }}
                path: {{ $key }}
              {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
