apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}-cluster
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.name" . }}
        release: {{ .Release.Name }}
        agentKind: cluster
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: cluster-agent
        image: "{{ .Values.cluster_agent.image.repository }}:{{ .Values.cluster_agent.image.tag }}"
        imagePullPolicy: {{ .Values.cluster_agent.image.pullPolicy }}
        command: ["/bin/sh","-c"]
        args: ["/app/kube-cluster"]
        resources:
{{ toYaml .Values.cluster_agent.resources | indent 12 }}
        ports:
        - name: socketserver
          containerPort: 1200
        volumeMounts:
          - name: config
            mountPath: /opt/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "sf-apm-agents.fullname" . }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
{{- if .Values.cluster_agent.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cluster_agent.nodeSelector | indent 8 }}
{{- end }}
