{{- if .Values.forwardmetric.enabled }}
{{- if .Values.forwardmetric.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}-forwarder
  labels:
    app: {{ template "sf-apm-forward.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sf-apm-forward.name" . }}
  minReplicas: {{ .Values.forwardmetric.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.forwardmetric.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.forwardmetric.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.forwardmetric.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.forwardmetric.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.forwardmetric.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
