apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring.fullname" . }}-nginx-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spring.name" . }}
    chart: {{ include "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: nginx
data:
  nginx.conf: |
    worker_processes  5;

    events {
        worker_connections  4096;
    }

    http {
        resolver "{{ .Values.nginx.resolver }}" valid=30s;

        default_type application/octet-stream;
        log_format upstream_time  '$remote_addr:$remote_port $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent" "$http_referer" '
                       'rt=$request_time uct=$upstream_connect_time uht=$upstream_header_time urt=$upstream_response_time';

        upstream backend {
            least_conn;
            server {{ template "spring.fullname" . }}-headless:{{ .Values.containerPort }};
        }

        server { 
            listen          80;
            error_log /var/log/nginx/error1.log;
            access_log /var/log/nginx/access1.log upstream_time;
            location / {
                proxy_pass      http://backend;
            }

            location /nginx_status {
                stub_status;
            }
        }
    }


      
