apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfapm.fullname" . }}-apm-celery-notify
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: celery
    queue: notify
    snappyflow/component: snappyflow-apm
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  replicas: {{ .Values.sfapm_celery.notify.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfapm.selectorLabels" . | nindent 6 }}
      app: sfapm
      role: celery
      queue: notify
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sfapm.selectorLabels" . | nindent 8 }}
        app: sfapm
        role: celery
        queue: notify
        snappyflow/component: snappyflow-apm
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sfapm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: pythonagent
          image: busybox
          command:
          - sh
          - -c
          - -x
          - wget -O /sfagent/sftrace-agent.tar.gz https://github.com/snappyflow/apm-agent/releases/download/latest/sftrace-agent.tar.gz && cd /sfagent && tar -xvzf sftrace-agent.tar.gz && rm sftrace-agent.tar.gz
          volumeMounts:
          - mountPath: /sfagent
            name: sftrace-agent
        - name: db-ready
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - "until pg_isready -d postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}; do sleep 3; done"
          {{- if .Values.postgresql.enabled }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
        - name: redis-ready
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - "until redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} ping ; do sleep 3; done"
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
      containers:
        - name: celery
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sfapm.image.repository }}:{{ .Values.sfapm.image.tag }}"
          imagePullPolicy: {{ .Values.sfapm.image.pullPolicy }}
          command:
          - sh
          - -c
          - /sfagent/sftrace/sftrace --sfcmd="{{ .Values.sfapm_celery.notify.command }}"
          env:
          {{- range $key, $value := .Values.sfapm_celery.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
            - name: SFTRACE_PROFILE_KEY
              value: "{{ .Values.global.key }}"
            - name: SFTRACE_PROJECT_NAME
              value: "{{ .Values.global.sfprojectname }}"
            - name: SFTRACE_APP_NAME
              value: "{{ .Values.global.sfappname }}"
            - name: ENABLE_SFTRACE
              value: "{{ .Values.global.enable_sftrace }}"
            - name: ELASTIC_APM_SERVICE_NAME
              value: "sfapm-celery-notify"
          {{- if .Values.postgresql.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: multidbUserPassord
          {{- end }}
          {{- if .Values.enableDebug }}
            - name: DEBUG
              value: "True"
          {{- end }}
          {{- if .Values.enableDebug }}
            - name: LOG_LEVEL
              value: debug
          {{- else }}
            - name: LOG_LEVEL
              value: info
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "sfapm.fullname" . }}-apm
          resources:
            {{- toYaml .Values.sfapm_celery.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/snappyflow
              name: data
            - mountPath: /sfagent
              name: sftrace-agent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: sftrace-agent
          emptyDir: {}

