apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sfapm.fullname" . }}-ui-sfagent
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
    app: sfapm
    role: ui
data:
  config.yaml: |+
    ---
    key: "{{ .Values.global.key }}"
    metrics:
      plugins:
      - name: nginx
        enabled: true
        interval: 300
        config:
          location: nginx_status
          port: 80
          secure: false
    logging:
      plugins:
      - name: nginx-access
        enabled: true
        config:
          log_path: "/var/log/nginx/access1.log"
      - name: nginx-error
        enabled: true
        config:
          log_path: "/var/log/nginx/error1.log"
