apiVersion: v1
name: elasticsearchv1
home: https://www.elastic.co/products/elasticsearch
version: 0.3.10
description: This Elasticsearch cluster supports 3 master nodes, 2 data nodes, and 2 client nodes. Data nodes use Persistent volumes. Includes monitoring of Pod metrics, Storage metrics, Elasticsearch cluster metrics, JVM metrics, and logs
icon: https://static-www.elastic.co/assets/blteb1c97719574938d/logo-elastic-elasticsearch-lt.svg
sources:
  - https://www.elastic.co/products/elasticsearch
  - https://github.com/pires/kubernetes-elasticsearch-cluster
maintainers:
  - name: Maplelabs
    email: Maplelabs
engine: gotpl
