apiVersion: v1
description: Official Elastic helm chart for Elastic APM Server
home: https://github.com/elastic/helm-charts
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: trace-server
version: 1.0.0
appVersion: 8.0.0-SNAPSHOT
sources:
  - https://github.com/elastic/apm
icon: https://helm.elastic.co/icons/apm.png
