apiVersion: v1
kind: Service
metadata:
  name: {{ include "cp-kafka.fullname" . }}-exporterser
  labels:
    app: {{ include "cp-kafka.name" . }}-exporterser
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: exporter
    snappyflow/plugin: kafka
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
  annotations:
    snappyflow/prometheus: 'true'
spec:
  ports:
  - name: kafka-exporter
    protocol: TCP
    port: 9308
    targetPort: 9308
  selector:
    app: {{ include "cp-kafka.fullname" . }}-exporter
    release: {{ .Release.Name }}
