rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if create is true, REQUIRED if create is false
  serviceAccountName: default

config:
  # unique cluster name to add in documents as _tag_cloudName
  cluster_name: kubernetes
  # project name label key, value of the label will be added in documents as _tag_projectName
  # projectname_label: snappyflow/projectname
  #
  # application name label key, value of the label will be added in documents as _tag_appName
  # appname_label: snappyflow/appname
  #
  # SnappyFlow APM Elasticsearch Target key copied from APM cloudprofile
  # This is used for application inventory documents, application heartbeats.
  key: ""
  #
  # SnappyFlow Key for cloud heartbeat and metrics, 
  # If not provided then key used
  # cloud_key: "cluster_key"

# HeartBeat and Inventory agent config
heartbeat:
  image:
    repository: snappyflowml/kube-inventory
    tag: latest
    pullPolicy: Always

  configmap:
    # Heartbeat and inventory interval, default 300 sec
    interval: 300
    #
    # If key is not provided
    # Elasticsearch target details to send inventory and heartbeat data
    #target: {}

  ## container resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi

  tolerations: []

  nodeSelector: {}

# Cluster monitoring
cluster_monitoring:
  enabled: true
  image:
    repository: snappyflowml/kube-cluster
    tag: latest
    pullPolicy: Always
  # if enabled
  configmap:
    # cluster monitoring interval, default is 300 seconds
    interval: 300
    # Tags to be added in cluster metrics document
    #tags: {}
    #target: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 512Mi

  tolerations: []

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

# Application monitoring.
application_monitoring:
  enabled: true
  prometheus_poller:
    image:
      repository: snappyflowml/kube-prom
      tag: latest
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 512Mi
  event_metrics:
    image:
      repository: snappyflowml/kube-events
      tag: latest
      pullPolicy: Always

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 512Mi
  storage_monitoring:
    image:
      repository: snappyflowml/kube-storage
      tag: latest
      pullPolicy: Always

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 256m
        memory: 512Mi

  tolerations: []

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  configmap:
    log_dir: /tmp
    interval: 300
    apps: {}
    #apps:
    #  demo-kube:
    #    petclinic:
    #      deployments: {}
    #      enabled: true
    #      tags:
    #        appName: petclinic
    #        projectName: demo-kube
    #      target:
    #        config:
    #          host: tf-lb-2020032314000363840
    #          index: demokube-66fzeofhdw-metric
    #          port: 9200
    #        name: demokube-metric
    #        type: elasticsearch

fluentbit:
  enabled: true
  drop_cluster_logs: false
  image:
    fluent_bit:
      repository: snappyflowml/fluentbit-sfapm
      tag: latest
    config:
      repository: snappyflowml/kube-fluent-init
      tag: latest
    pullPolicy: Always

  podAnnotations: {}

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 10m
    #   memory: 8Mi

  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: NoSchedule

  nodeSelector: {}

