apiVersion: v1
kind: Service
metadata:
  name: {{ include "charging.fullname" . }}
  labels:
    {{- include "charging.labels" . | nindent 4 }}
    service: charging
    snappyflow/component: charging
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "charging.selectorLabels" . | nindent 4 }}
    service: charging
