apiVersion: v1
name: sfagent
version: 3.1.17
appVersion: "2.1"
description: Cluster and Application Monitoring and Logging system for Maplelabs' snappyFlow APM.
home: http://www.snappyflow.io
keywords:
- monitoring
- alerting
- metric
- logging
maintainers:
  - name: Upendra
    email: upendra.sahu@maplelabs.com
engine: gotpl

